name: Native-AMD64

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true
      #Build Image
      - name: Build Image
        run: ./mvnw -Pproduction -Pnative spring-boot:build-image
      #Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #Deploy the image to the Docker registry
      - name: Push Images to Docker Registry
        run: docker push -a dashaun/hilla-aot-demo


  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: pull-arm64
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 6
          command: docker pull dashaun/hilla-aot-demo:1.0-SNAPSHOT-aarch_64
      - name: create-manifest
        run: |
          docker manifest create dashaun/hilla-aot-demo:1.0-SNAPSHOT --amend dashaun/hilla-aot-demo:1.0-SNAPSHOT-x86_64 --amend dashaun/hilla-aot-demo:1.0-SNAPSHOT-aarch_64
          docker manifest push dashaun/hilla-aot-demo:1.0-SNAPSHOT
          docker manifest create dashaun/hilla-aot-demo:latest --amend dashaun/hilla-aot-demo:1.0-SNAPSHOT-x86_64 --amend dashaun/hilla-aot-demo:1.0-SNAPSHOT-aarch_64
          docker manifest push dashaun/hilla-aot-demo:latest